version: '3.5'

services:
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis
      PORT: 8080
      REQUEST_ORIGIN: http://localhost:5000
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: postgres
    depends_on:
      - db

  frontend:
    image: frontend
    ports:
      - 5000:5000

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - data:/data

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: postgres_db
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
  data:
