version: '3.5'

services:
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000

  frontend:
    image: frontend
    ports:
      - 5000:5000

  redis:
    image: redis
    restart: unless-stopped
